export const techStack = [
  'Next.js',
  'React',
  'React DOM',
  'TypeScript',
  'Zustand',
  'SCSS',
  'React Hook Form',
  'Zod',
  'Next-intl',
  'Vitest',
  'React Testing Library',
  'JSDOM',
  'V8 Coverage',
  'Husky',
  'Lint-staged',
  'Commitlint',
  'Validate Branch Name',
  'ESLint',
  'Prettier',
];
