import { Column, RequestLog } from '@/types/historyTypes';
import { formatDuration, formatSize, getMethodKey, getStatusTone } from '@/utils/historyUtils';

export const emptyLogs: RequestLog[] = [];

export const columns: Column<RequestLog>[] = [
  {
    key: 'method',
    label: 'Method',
    textProps: {
      size: 'xxxs',
      weight: 'bold',
      classNameElement: 'method',
      getValueElement: (el) => el.method,
      getDataAttributes: (el) => ({ 'data-method': getMethodKey(el.method) }),
    },
  },
  {
    key: 'endpoint',
    label: 'Endpoint',
    textProps: {
      size: 'xxs',
      weight: 'medium',
      classNameElement: 'endpoint',
      getValueElement: (el) => el.endpoint,
    },
  },
  {
    key: 'status',
    label: 'Status',
    textProps: {
      size: 'xxs',
      weight: 'bold',
      classNameElement: 'status',
      getValueElement: (el) => String(el.statusCode),
      getDataAttributes: (el) => ({ 'data-tone': getStatusTone(el.statusCode) }),
    },
  },
  {
    key: 'duration',
    label: 'Duration',
    textProps: {
      size: 'xxs',
      weight: 'medium',
      classNameElement: 'cell',
      getValueElement: (el) => formatDuration(el.durationMs),
    },
  },
  {
    key: 'reqSize',
    label: 'Req. size',
    textProps: {
      size: 'xxs',
      weight: 'medium',
      classNameElement: 'cell',
      getValueElement: (el) => formatSize(el.requestSize),
    },
  },
  {
    key: 'resSize',
    label: 'Res. size',
    textProps: {
      size: 'xxs',
      weight: 'medium',
      classNameElement: 'cell',
      getValueElement: (el) => formatSize(el.responseSize),
    },
  },
  {
    key: 'timestamp',
    label: 'Timestamp',
    textProps: {
      size: 'xxs',
      weight: 'medium',
      classNameElement: 'cell',
      getValueElement: (el) =>
        new Date(el.timestamp).toLocaleString('sv-GB', {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }),
    },
  },
];

export const mockLogs: RequestLog[] = [
  {
    id: '2',
    userId: 'u1',
    method: 'GET',
    endpoint: '/pet/findByStatus',
    url: 'https://petstore3.swagger.io/api/v3/pet/findByStatus',
    statusCode: 200,
    durationMs: 142,
    requestSize: 0,
    responseSize: 4200,
    timestamp: '2026-06-27T18:41:55Z',
    errorDetails: null,
  },
  {
    id: '3',
    userId: 'u1',
    method: 'GET',
    endpoint: '/pet/9223372036854',
    url: 'https://petstore3.swagger.io/api/v3/pet/9223372036854',
    statusCode: 404,
    durationMs: 96,
    requestSize: 0,
    responseSize: 142,
    timestamp: '2026-06-27T18:40:12Z',
    errorDetails: 'Pet not found',
  },
  {
    id: '4',
    userId: 'u1',
    method: 'PUT',
    endpoint: '/pet',
    url: 'https://petstore3.swagger.io/api/v3/pet',
    statusCode: 200,
    durationMs: 173,
    requestSize: 448,
    responseSize: 880,
    timestamp: '2026-06-27T18:38:47Z',
    errorDetails: null,
  },
  {
    id: '5',
    userId: 'u1',
    method: 'PATCH',
    endpoint: '/pet/10',
    url: 'https://petstore3.swagger.io/api/v3/pet/10',
    statusCode: 200,
    durationMs: 118,
    requestSize: 96,
    responseSize: 880,
    timestamp: '2026-06-27T18:36:20Z',
    errorDetails: null,
  },
  {
    id: '6',
    userId: 'u1',
    method: 'DELETE',
    endpoint: '/pet/10',
    url: 'https://petstore3.swagger.io/api/v3/pet/10',
    statusCode: 200,
    durationMs: 104,
    requestSize: 0,
    responseSize: 0,
    timestamp: '2026-06-27T18:35:02Z',
    errorDetails: null,
  },
  {
    id: '1',
    userId: 'u1',
    method: 'POST',
    endpoint: '/pet',
    url: 'https://petstore3.swagger.io/api/v3/pet',
    statusCode: 201,
    durationMs: 128,
    requestSize: 412,
    responseSize: 880,
    timestamp: '2026-06-27T18:42:09Z',
    errorDetails: null,
  },
  {
    id: '7',
    userId: 'u1',
    method: 'POST',
    endpoint: '/user/createWithList',
    url: 'https://petstore3.swagger.io/api/v3/user/createWithList',
    statusCode: 500,
    durationMs: 2410,
    requestSize: 1200,
    responseSize: 318,
    timestamp: '2026-06-27T18:31:44Z',
    errorDetails: 'Internal server error',
  },
  {
    id: '8',
    userId: 'u1',
    method: 'GET',
    endpoint: '/store/inventory',
    url: 'https://petstore3.swagger.io/api/v3/store/inventory',
    statusCode: 200,
    durationMs: 88,
    requestSize: 0,
    responseSize: 612,
    timestamp: '2026-06-27T18:29:10Z',
    errorDetails: null,
  },
];
