export const skillsList = [
  'JavaScript',
  'TypeScript',
  'Git, GitHub (clone, add, commit, push, pull, merge, rebase, pull request flow)',
  'NPM, Webpack',
  'CSS3 / HTML5',
  'Chrome DevTools, Figma',
  'Understanding of how to interact with APIs (general understanding of REST and GraphQL)',
];

export const techStack = [
  'Next.js',
  'React',
  'React DOM',
  'TypeScript',
  'Zustand',
  'SCSS',
  'React Hook Form',
  'Zod',
  'Next-intl',
  'Vitest',
  'React Testing Library',
  'JSDOM',
  'V8 Coverage',
  'Husky',
  'Lint-staged',
  'Commitlint',
  'Validate Branch Name',
  'ESLint',
  'Prettier',
];
